"use client";
import { useEffect,useState,useRef } from 'react';
import { FormProvider,useForm,useWatch } from 'react-hook-form';
import { createEmptyResumeContent,resumeContentFormSchema,type ResumeContent } from '@/lib/validations/resume';
import type { AdminDocument,AdminDocumentPayload } from '@/lib/admin/documents/schema';
import { ResumeTypeSelector } from '@/components/resume/resume-type-selector';
import { ResumeLengthSelector } from '@/components/resume/resume-length-selector';
import { ResumePreview } from '@/components/resume/resume-preview';
import { templatesForType,getTemplate } from '@/lib/resume/templates';
import { ContactSection } from '@/components/forms/resume-sections/contact-section';
import { SummarySection } from '@/components/forms/resume-sections/summary-section';
import { ExperienceSection } from '@/components/forms/resume-sections/experience-section';
import { EducationSection } from '@/components/forms/resume-sections/education-section';
import { SkillsSection } from '@/components/forms/resume-sections/skills-section';
import { ProjectsSection } from '@/components/forms/resume-sections/projects-section';
import { CertificationsSection } from '@/components/forms/resume-sections/certifications-section';
import { LanguagesSection } from '@/components/forms/resume-sections/languages-section';
import { Button } from '@/components/ui/button';
const input='mt-1 w-full rounded-lg border border-border bg-background px-3 py-2 text-sm';
const sections={Contact:ContactSection,Summary:SummarySection,Experience:ExperienceSection,Education:EducationSection,Skills:SkillsSection,Projects:ProjectsSection,Certifications:CertificationsSection,Languages:LanguagesSection};
export function AdminDocumentWorkspace({kind,clients}:{kind:'resume'|'cover_letter';clients:{id:string;label:string}[]}){
 const pending=useRef(false);
 const methods=useForm<ResumeContent>({defaultValues:createEmptyResumeContent()});
 const content=useWatch({control:methods.control}) as ResumeContent;
 const [id,setId]=useState(''),[title,setTitle]=useState(kind==='resume'?'Untitled resume':'Untitled cover letter'),[templateId,setTemplate]=useState('classic');
 const [letter,setLetter]=useState(''),[jobDescription,setJobDescription]=useState(''),[company,setCompany]=useState(''),[jobTitle,setJobTitle]=useState('');
 const [clientId,setClient]=useState(''),[step,setStep]=useState(0),[tab,setTab]=useState<keyof typeof sections>('Contact');
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[savedSnapshot,setSavedSnapshot]=useState('');
 const [library,setLibrary]=useState<Omit<AdminDocument,'payload'>[]>([]),[libraryError,setLibraryError]=useState('');
 const payload:AdminDocumentPayload={resume:content,letter,templateId,jobDescription,company,jobTitle};
 const snapshot=JSON.stringify({title,payload});
 const hasWork=!!(content.contact?.full_name||content.summary?.text||content.experience?.length||content.custom_sections?.length||letter||jobDescription);
 const dirty=hasWork&&snapshot!==savedSnapshot;
 useEffect(()=>{const handler=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler);},[dirty]);
 async function libraryList(){try{const r=await fetch('/api/admin/document-workspace');const body=await r.json();if(!r.ok)throw Error(body.error?.message||'Library unavailable.');setLibrary(body.data);setLibraryError('');}catch(e){setLibraryError(e instanceof Error?e.message:'Library unavailable.');}}
 useEffect(()=>{void libraryList();},[]);
 function body(){const parsed=resumeContentFormSchema.safeParse(methods.getValues());if(!parsed.success)throw Error(`Check your resume: ${parsed.error.issues[0]?.path.join('.')} ${parsed.error.issues[0]?.message}`);if(!title.trim())throw Error('Enter a document title.');return {id:id||crypto.randomUUID(),kind,title:title.trim(),payload:{...payload,resume:parsed.data},clientId:clientId||null};}
 async function json(url:string,value:unknown){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)});const data=await r.json();if(!r.ok)throw Error(data.error?.message||'Request failed.');return data.data;}
 async function run(work:()=>Promise<void>){if(pending.current)return;pending.current=true;setBusy(true);setError('');setNotice('');try{await work();}catch(e){setError(e instanceof Error?e.message:'Please retry.');}finally{pending.current=false;setBusy(false);}}
 async function upload(file:File){await run(async()=>{const form=new FormData();form.set('file',file);const r=await fetch('/api/admin/document-workspace/upload',{method:'POST',body:form});const result=await r.json();if(!r.ok)throw Error(result.error?.message||'Upload failed.');methods.reset({...result.data.content,resume_type:content.resume_type||'corporate'});setNotice(result.data.warning);setTab('Summary');});}
 async function generate(){await run(async()=>{const data=await json('/api/admin/document-workspace/generate',{kind,payload:body().payload});if(kind==='resume')methods.reset(data.content);else setLetter(data.letter);setNotice(data.warning||'Draft generated. Review and edit before saving or downloading.');setStep(2);});}
 async function download(format:'pdf'|'docx',document=body()){
  const r=await fetch('/api/admin/document-workspace/export',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...document,format})});
  if(!r.ok){const result=await r.json();throw Error(result.error?.message||'Download failed.');}
  const url=URL.createObjectURL(await r.blob()),a=documentNode();a.href=url;a.download=`${document.title.replace(/[^a-zA-Z0-9_-]/g,'_')}.${format}`;a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);
 }
 function documentNode(){const a=window.document.createElement('a');window.document.body.appendChild(a);return a;}
 async function save(andDownload=false){await run(async()=>{const document=body();setId(document.id);await json('/api/admin/document-workspace',document);setSavedSnapshot(snapshot);setNotice(clientId?'Saved to your library and copied to the selected client.':'Saved to your private library.');await libraryList();if(andDownload){try{await download('pdf',document);}catch(e){throw Error(`Saved successfully, but ${e instanceof Error?e.message:'download failed'}. Use Download to retry without saving again.`);}}});}
 function newDraft(){if(dirty&&!window.confirm('Discard unsaved changes and start another document?'))return;methods.reset(createEmptyResumeContent());setId('');setTitle(kind==='resume'?'Untitled resume':'Untitled cover letter');setTemplate('classic');setLetter('');setJobDescription('');setJobTitle('');setCompany('');setClient('');setStep(0);setTab('Contact');setSavedSnapshot('');setNotice('New unsaved draft.');setError('');}
 async function open(docId:string){if(dirty&&!window.confirm('Discard unsaved changes and open the saved document?'))return;await run(async()=>{const r=await fetch(`/api/admin/document-workspace?id=${docId}`),result=await r.json();if(!r.ok)throw Error(result.error?.message||'Unable to open.');const d=result.data as AdminDocument;if(d.kind!==kind)throw Error('Open this document in the other creator.');methods.reset(d.payload.resume);setId(d.id);setTitle(d.title);setTemplate(d.payload.templateId);setLetter(d.payload.letter);setJobDescription(d.payload.jobDescription);setCompany(d.payload.company);setJobTitle(d.payload.jobTitle);setClient('');setSavedSnapshot(JSON.stringify({title:d.title,payload:d.payload}));setStep(2);});}
 async function remove(docId:string){if(!window.confirm('Permanently delete this library document? Client copies will remain.'))return;if(!window.confirm('Confirm permanent deletion. This library document cannot be recovered.'))return;await run(async()=>{const r=await fetch(`/api/admin/document-workspace?id=${docId}`,{method:'DELETE'});if(!r.ok)throw Error('Unable to delete.');if(docId===id){setId('');setSavedSnapshot('');}await libraryList();setNotice('Library document deleted.');});}
 const Section=sections[tab];
 return <div className="mx-auto max-w-7xl space-y-6"><header className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-3xl font-semibold">Create {kind==='resume'?'resume':'cover letter'}</h1><p className="mt-2 text-sm text-text-secondary">Your standalone workspace. Uploading, generating and downloading do not save a document. Save explicitly to keep a copy.</p></div><Button variant="secondary" disabled={busy} onClick={newDraft}>New draft</Button></header>
 <details className="rounded-xl border border-border p-4"><summary className="cursor-pointer font-medium">My saved {kind==='resume'?'resumes':'cover letters'}</summary>{libraryError&&<p role="alert" className="mt-3 text-sm text-error">{libraryError}</p>}<ul className="mt-3 space-y-2">{library.filter(d=>d.kind===kind).map(d=><li key={d.id} className="flex justify-between gap-3 text-sm"><button disabled={busy} onClick={()=>open(d.id)} className="text-left underline">{d.title} · {new Date(d.updated_at).toLocaleDateString()}</button><button disabled={busy} onClick={()=>remove(d.id)} className="text-error">Delete</button></li>)}</ul></details>
 <nav aria-label="Creation steps" className="flex flex-wrap gap-2">{['Source & category','Tailor','Review & export'].map((label,i)=><button key={label} disabled={busy} onClick={()=>setStep(i)} aria-current={step===i?'step':undefined} className={`rounded-lg border px-4 py-2 text-sm ${step===i?'border-primary bg-primary/10':'border-border'}`}>{i+1}. {label}</button>)}</nav>
 {error&&<p role="alert" className="rounded-lg border border-error/30 p-3 text-sm text-error">{error}</p>}{notice&&<p role="status" className="rounded-lg border border-border p-3 text-sm">{notice}</p>}
 <fieldset disabled={busy} className="space-y-5"><label className="block text-sm">Document title<input value={title} onChange={e=>setTitle(e.target.value)} maxLength={200} className={input}/></label>
 {step===0&&<><ResumeTypeSelector value={content.resume_type||'corporate'} onChange={type=>{methods.setValue('resume_type',type,{shouldDirty:true});setTemplate(type==='c2c'?'c2c-consultant':'classic');}}/><label className="block rounded-xl border border-dashed border-border p-4 text-sm">Upload a source resume (PDF or Word, up to 4 MB)<input type="file" accept=".pdf,.docx" className="mt-3 block w-full text-sm" onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file);e.target.value='';}}/></label><p className="text-xs text-text-secondary">Or enter the candidate&apos;s details below. No source file is retained in storage.</p></>}
 {step===1&&<><label className="block text-sm">Target company<input value={company} onChange={e=>setCompany(e.target.value)} className={input} maxLength={200}/></label><label className="block text-sm">Target job title<input value={jobTitle} onChange={e=>setJobTitle(e.target.value)} className={input} maxLength={200}/></label><label className="block text-sm">Job description (optional)<textarea value={jobDescription} onChange={e=>setJobDescription(e.target.value)} rows={8} maxLength={15000} className={input}/></label><p className="text-sm text-text-secondary">{kind==='resume'&&content.resume_type==='c2c'?'AI will tailor only the professional summary. Other sections remain unchanged, even when they require more pages.':'Generation uses the candidate details you supplied. Review the draft for accuracy.'}</p><Button onClick={generate} isLoading={busy}>Generate {kind==='resume'?'resume':'cover letter'}</Button></>}
 {(step===0||step===2)&&<div className="grid min-w-0 gap-6 xl:grid-cols-2"><div className="min-w-0 space-y-4">{step===2&&kind==='cover_letter'?<label className="block text-sm">Edit cover letter<textarea value={letter} onChange={e=>setLetter(e.target.value)} rows={22} maxLength={30000} className={input}/></label>:<FormProvider {...methods}><div className="flex flex-wrap gap-2" role="tablist" aria-label="Resume sections">{Object.keys(sections).map(name=><button type="button" role="tab" aria-selected={tab===name} key={name} onClick={()=>setTab(name as keyof typeof sections)} className={`rounded-lg px-3 py-2 text-xs ${tab===name?'bg-primary text-white':'bg-surface border border-border'}`}>{name}</button>)}</div><Section/><details><summary className="mt-4 cursor-pointer text-sm">Additional information</summary>{(content.custom_sections||[]).map((section,i)=><div key={section.id} className="mt-3"><input aria-label="Section title" {...methods.register(`custom_sections.${i}.title`)} className={input}/><textarea aria-label="Section content" {...methods.register(`custom_sections.${i}.content`)} rows={6} className={input}/></div>)}<Button variant="secondary" onClick={()=>methods.setValue('custom_sections',[...(content.custom_sections||[]),{id:crypto.randomUUID(),title:'Additional information',content:''}],{shouldDirty:true})}>Add section</Button></details></FormProvider>}</div><div className="min-w-0 overflow-auto rounded-xl border border-border p-3">{kind==='resume'?<><label className="block text-sm">Layout<select value={templateId} onChange={e=>setTemplate(e.target.value)} className={input}>{templatesForType(content.resume_type||'corporate').map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select></label><div className="my-4"><ResumeLengthSelector value={content.layout?.target_pages??null} onChange={pages=>methods.setValue('layout',{target_pages:pages},{shouldDirty:true})}/></div><ResumePreview content={content} templateId={getTemplate(templateId).id}/></>:<div className="min-h-80 whitespace-pre-wrap rounded-lg bg-white p-6 text-sm leading-7 text-slate-900">{letter||'The cover letter preview will appear here after generation or editing.'}</div>}</div></div>}
 {step===2&&<section className="space-y-4 rounded-xl border border-border p-4"><label className="block text-sm">Optional client copy<select value={clientId} onChange={e=>setClient(e.target.value)} className={input}><option value="">Private library only</option>{clients.map(c=><option value={c.id} key={c.id}>{c.label}</option>)}</select></label><p className="text-xs text-text-secondary">Saving with a selected client also creates or updates their copy. Downloads alone leave both libraries unchanged.</p><div className="flex flex-wrap gap-3"><Button onClick={()=>save()}>Save to library{clientId?' & client':''}</Button><Button onClick={()=>save(true)}>Save & download PDF</Button><Button variant="secondary" onClick={()=>run(()=>download('pdf'))}>Download PDF only</Button><Button variant="secondary" onClick={()=>run(()=>download('docx'))}>Download Word only</Button></div><p className="text-xs text-text-secondary">{dirty?'Unsaved changes':savedSnapshot?'Saved':'Not saved yet'}</p></section>}
 {step<2&&<Button variant="secondary" onClick={()=>setStep(step+1)}>Continue</Button>}
 </fieldset>{busy&&<p role="status" className="text-sm">Working… Your draft stays editable when this finishes.</p>}</div>;
}
