"use client";
import { useEffect,useState,useRef } from 'react';
import { FormProvider,useForm,useWatch } from 'react-hook-form';
import { createEmptyResumeContent,resumeContentFormSchema,type ResumeContent } from '@/lib/validations/resume';
import type { AdminDocument,AdminDocumentPayload } from '@/lib/admin/documents/schema';
import { ResumeTypeSelector } from '@/components/resume/resume-type-selector';
import { ResumeLengthSelector } from '@/components/resume/resume-length-selector';
import { ResumePreview } from '@/components/resume/resume-preview';
import { templatesForType,getTemplate } from '@/lib/resume/templates';
import { ContactSection } from '@/components/forms/resume-sections/contact-section';
import { SummarySection } from '@/components/forms/resume-sections/summary-section';
import { ExperienceSection } from '@/components/forms/resume-sections/experience-section';
import { EducationSection } from '@/components/forms/resume-sections/education-section';
import { SkillsSection } from '@/components/forms/resume-sections/skills-section';
import { ProjectsSection } from '@/components/forms/resume-sections/projects-section';
import { CertificationsSection } from '@/components/forms/resume-sections/certifications-section';
import { LanguagesSection } from '@/components/forms/resume-sections/languages-section';
import { Button } from '@/components/ui/button';
import { ArrowRight, Check, Download, FileText, FolderOpen, Plus, Save, Sparkles, UploadCloud, Trash2 } from 'lucide-react';
import { PAPER } from '@/lib/resume/layout';
const input='mt-2 w-full min-w-0 rounded-xl border border-border bg-background px-3 py-2.5 text-sm transition focus:border-primary/60 focus:outline-none focus:ring-2 focus:ring-primary/20';
const card='min-w-0 rounded-2xl border border-border bg-surface p-5 shadow-sm sm:p-6';
const sections={Contact:ContactSection,Summary:SummarySection,Experience:ExperienceSection,Education:EducationSection,Skills:SkillsSection,Projects:ProjectsSection,Certifications:CertificationsSection,Languages:LanguagesSection};
export function AdminDocumentWorkspace({kind,clients}:{kind:'resume'|'cover_letter';clients:{id:string;label:string}[]}){
 const pending=useRef(false);
 const previewRef=useRef<HTMLDivElement>(null);
 const [previewWidth,setPreviewWidth]=useState(600),[zoom,setZoom]=useState<number|null>(null);
 useEffect(()=>{const element=previewRef.current;if(!element)return;const observer=new ResizeObserver(([entry])=>setPreviewWidth(entry.contentRect.width));observer.observe(element);return()=>observer.disconnect();},[]);
 const previewScale=zoom??Math.min(1,Math.max(.2,(previewWidth-32)/PAPER.width));
 const methods=useForm<ResumeContent>({defaultValues:createEmptyResumeContent()});
 const content=useWatch({control:methods.control}) as ResumeContent;
 const [id,setId]=useState(''),[title,setTitle]=useState(kind==='resume'?'Untitled resume':'Untitled cover letter'),[templateId,setTemplate]=useState('classic');
 const [letter,setLetter]=useState(''),[jobDescription,setJobDescription]=useState(''),[company,setCompany]=useState(''),[jobTitle,setJobTitle]=useState('');
 const [clientId,setClient]=useState(''),[step,setStep]=useState(0),[tab,setTab]=useState<keyof typeof sections>('Contact');
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[savedSnapshot,setSavedSnapshot]=useState('');
 const [library,setLibrary]=useState<Omit<AdminDocument,'payload'>[]>([]),[libraryError,setLibraryError]=useState('');
 const payload:AdminDocumentPayload={resume:content,letter,templateId,jobDescription,company,jobTitle};
 const snapshot=JSON.stringify({title,payload});
 const hasWork=!!(content.contact?.full_name||content.summary?.text||content.experience?.length||content.custom_sections?.length||letter||jobDescription);
 const dirty=hasWork&&snapshot!==savedSnapshot;
 useEffect(()=>{const handler=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler);},[dirty]);
 async function libraryList(){try{const r=await fetch('/api/admin/document-workspace');const body=await r.json();if(!r.ok)throw Error(body.error?.message||'Library unavailable.');setLibrary(body.data);setLibraryError('');}catch(e){setLibraryError(e instanceof Error?e.message:'Library unavailable.');}}
 useEffect(()=>{void libraryList();},[]);
 function body(){const parsed=resumeContentFormSchema.safeParse(methods.getValues());if(!parsed.success)throw Error(`Check your resume: ${parsed.error.issues[0]?.path.join('.')} ${parsed.error.issues[0]?.message}`);if(!title.trim())throw Error('Enter a document title.');return {id:id||crypto.randomUUID(),kind,title:title.trim(),payload:{...payload,resume:parsed.data},clientId:clientId||null};}
 async function json(url:string,value:unknown){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)});const data=await r.json();if(!r.ok)throw Error(data.error?.message||'Request failed.');return data.data;}
 async function run(work:()=>Promise<void>){if(pending.current)return;pending.current=true;setBusy(true);setError('');setNotice('');try{await work();}catch(e){setError(e instanceof Error?e.message:'Please retry.');}finally{pending.current=false;setBusy(false);}}
 async function upload(file:File){await run(async()=>{const form=new FormData();form.set('file',file);const r=await fetch('/api/admin/document-workspace/upload',{method:'POST',body:form});const result=await r.json();if(!r.ok)throw Error(result.error?.message||'Upload failed.');methods.reset({...result.data.content,resume_type:content.resume_type||'corporate'});setNotice(result.data.warning);setTab('Summary');});}
 async function generate(){await run(async()=>{const data=await json('/api/admin/document-workspace/generate',{kind,payload:body().payload});if(kind==='resume')methods.reset(data.content);else setLetter(data.letter);setNotice(data.warning||'Draft generated. Review and edit before saving or downloading.');setStep(2);});}
 async function download(format:'pdf'|'docx',document=body()){
  const r=await fetch('/api/admin/document-workspace/export',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...document,format})});
  if(!r.ok){const result=await r.json();throw Error(result.error?.message||'Download failed.');}
  const url=URL.createObjectURL(await r.blob()),a=documentNode();a.href=url;a.download=`${document.title.replace(/[^a-zA-Z0-9_-]/g,'_')}.${format}`;a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);
 }
 function documentNode(){const a=window.document.createElement('a');window.document.body.appendChild(a);return a;}
 async function save(andDownload=false){await run(async()=>{const document=body();setId(document.id);await json('/api/admin/document-workspace',document);setSavedSnapshot(snapshot);setNotice(clientId?'Saved to your library and copied to the selected client.':'Saved to your private library.');await libraryList();if(andDownload){try{await download('pdf',document);}catch(e){throw Error(`Saved successfully, but ${e instanceof Error?e.message:'download failed'}. Use Download to retry without saving again.`);}}});}
 function newDraft(){if(dirty&&!window.confirm('Discard unsaved changes and start another document?'))return;methods.reset(createEmptyResumeContent());setId('');setTitle(kind==='resume'?'Untitled resume':'Untitled cover letter');setTemplate('classic');setLetter('');setJobDescription('');setJobTitle('');setCompany('');setClient('');setStep(0);setTab('Contact');setSavedSnapshot('');setNotice('New unsaved draft.');setError('');}
 async function open(docId:string){if(dirty&&!window.confirm('Discard unsaved changes and open the saved document?'))return;await run(async()=>{const r=await fetch(`/api/admin/document-workspace?id=${docId}`),result=await r.json();if(!r.ok)throw Error(result.error?.message||'Unable to open.');const d=result.data as AdminDocument;if(d.kind!==kind)throw Error('Open this document in the other creator.');methods.reset(d.payload.resume);setId(d.id);setTitle(d.title);setTemplate(d.payload.templateId);setLetter(d.payload.letter);setJobDescription(d.payload.jobDescription);setCompany(d.payload.company);setJobTitle(d.payload.jobTitle);setClient('');setSavedSnapshot(JSON.stringify({title:d.title,payload:d.payload}));setStep(2);});}
 async function remove(docId:string){if(!window.confirm('Permanently delete this library document? Client copies will remain.'))return;if(!window.confirm('Confirm permanent deletion. This library document cannot be recovered.'))return;await run(async()=>{const r=await fetch(`/api/admin/document-workspace?id=${docId}`,{method:'DELETE'});if(!r.ok)throw Error('Unable to delete.');if(docId===id){setId('');setSavedSnapshot('');}await libraryList();setNotice('Library document deleted.');});}
 const Section=sections[tab];
 const noun=kind==='resume'?'resume':'cover letter';
 const savedDocuments=library.filter(d=>d.kind===kind);
 return <div className="mx-auto max-w-[1600px] space-y-6">
  <header className="flex flex-wrap items-start justify-between gap-4 border-b border-border pb-6">
   <div><div className="mb-3 h-1 w-10 rounded-full bg-gradient-to-r from-primary to-accent"/><p className="mb-2 text-xs font-semibold uppercase tracking-[.18em] text-text-secondary">Admin workspace</p><h1 className="font-display text-3xl font-semibold tracking-tight sm:text-4xl">Create {noun}</h1><p className="mt-2 max-w-xl text-sm leading-6 text-text-secondary">Build a polished {noun}, make it your own, and save it when you&apos;re ready.</p></div>
   <div className="flex items-center gap-3"><span className="rounded-full border border-border bg-surface px-3 py-1.5 text-xs text-text-secondary">{dirty?'Unsaved changes':savedSnapshot?'Saved to library':'New draft'}</span><Button variant="secondary" disabled={busy} onClick={newDraft} leftIcon={<Plus className="h-4 w-4"/>}>New draft</Button></div>
  </header>
  <nav aria-label="Creation steps" className="grid grid-cols-3 gap-2 sm:gap-4">{[['Source & category','Start with candidate details'],['Tailor','Add the target opportunity'],['Review & export','Refine, save and download']].map(([label,description],i)=><button key={label} disabled={busy} onClick={()=>setStep(i)} aria-current={step===i?'step':undefined} className={`flex min-w-0 items-center gap-3 rounded-2xl border p-3 text-left transition sm:p-4 ${step===i?'border-primary/50 bg-primary/5 shadow-sm':'border-border bg-surface hover:border-primary/30'}`}><span className={`hidden h-9 w-9 shrink-0 items-center justify-center rounded-xl text-sm font-semibold sm:flex ${step===i?'bg-primary text-white':'bg-muted text-text-secondary'}`}>{String(i+1).padStart(2,'0')}</span><span><span className={`block text-xs font-semibold sm:text-sm ${step===i?'text-primary':''}`}>{label}</span><span className="mt-1 hidden text-xs text-text-secondary sm:block">{description}</span></span></button>)}</nav>
  {error&&<p role="alert" className="rounded-xl border border-error/30 bg-error/5 p-4 text-sm text-error">{error}</p>}{notice&&<p role="status" className="flex items-start gap-2 rounded-xl border border-border bg-surface p-4 text-sm"><Check className="mt-0.5 h-4 w-4 shrink-0 text-primary"/>{notice}</p>}
  <fieldset disabled={busy} className="grid min-w-0 items-start gap-6 xl:grid-cols-[minmax(0,440px)_minmax(0,1fr)]">
   <div className="min-w-0 space-y-5">
    <section className={card}><h2 className="mb-4 flex items-center gap-2 font-semibold"><FileText className="h-4 w-4 text-primary"/>Document details</h2><label className="block text-sm font-medium">Document title<input value={title} onChange={e=>setTitle(e.target.value)} maxLength={200} className={input}/></label>{step===0&&<div className="mt-5 space-y-5"><ResumeTypeSelector value={content.resume_type||'corporate'} onChange={type=>{methods.setValue('resume_type',type,{shouldDirty:true});setTemplate(type==='c2c'?'c2c-consultant':'classic');}}/><label className={`relative block rounded-2xl border-2 border-dashed border-border bg-background/40 p-5 text-center transition focus-within:ring-2 focus-within:ring-primary/40 ${busy?'opacity-50':'cursor-pointer hover:border-primary/50 hover:bg-primary/5'}`}><UploadCloud className="mx-auto mb-3 h-7 w-7 text-primary"/><span className="block text-sm font-semibold">Upload a source resume</span><span className="mt-1 block text-xs text-text-secondary">PDF or Word (.docx), up to 4 MB</span><span className="mt-4 inline-block rounded-lg border border-primary/30 bg-primary/10 px-4 py-2 text-xs font-semibold text-primary">Browse files</span><input aria-label="Upload a source resume" type="file" accept=".pdf,.docx" className="absolute inset-0 h-full w-full cursor-pointer opacity-0 disabled:cursor-wait" onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file);e.target.value='';}}/></label><p className="text-xs leading-5 text-text-secondary">Or enter details below. Source files are used to fill this draft and are not retained.</p></div>}</section>
    {step===1&&<section className={`${card} space-y-5`}><div><h2 className="flex items-center gap-2 font-semibold"><Sparkles className="h-4 w-4 text-primary"/>Tailor to the opportunity</h2><p className="mt-1 text-xs leading-5 text-text-secondary">Give your draft a clear focus with the role and its requirements.</p></div><label className="block text-sm font-medium">Target company<input placeholder="e.g. Microsoft" value={company} onChange={e=>setCompany(e.target.value)} className={input} maxLength={200}/></label><label className="block text-sm font-medium">Target job title<input placeholder="e.g. Senior Business Analyst" value={jobTitle} onChange={e=>setJobTitle(e.target.value)} className={input} maxLength={200}/></label><label className="block text-sm font-medium">Job description (optional)<textarea placeholder="Paste responsibilities, skills and qualifications..." value={jobDescription} onChange={e=>setJobDescription(e.target.value)} rows={9} maxLength={15000} className={input}/></label><p className="rounded-xl bg-primary/5 p-3 text-xs leading-5 text-text-secondary">{kind==='resume'&&content.resume_type==='c2c'?'Only the professional summary is tailored. Your contract experience and all other sections stay unchanged.':'Generation uses the candidate details you supplied. Review the draft for accuracy.'}</p><Button className="w-full" onClick={generate} isLoading={busy} leftIcon={<Sparkles className="h-4 w-4"/>}>Generate {noun}</Button></section>}
    {(step===0||step===2)&&<section className={card}><div className="mb-5"><h2 className="font-semibold">{step===2?'Refine your draft':'Candidate details'}</h2><p className="mt-1 text-xs leading-5 text-text-secondary">{step===2?'Make your final edits and check the live preview.':'Add or review the experience behind this document.'}</p></div>{step===2&&kind==='cover_letter'?<label className="block text-sm font-medium">Edit cover letter<textarea value={letter} onChange={e=>setLetter(e.target.value)} rows={22} maxLength={30000} className={`${input} leading-7`}/></label>:<FormProvider {...methods}><div className="mb-5 flex flex-wrap gap-1.5 border-b border-border pb-4" role="tablist" aria-label="Resume sections">{Object.keys(sections).map(name=><button type="button" role="tab" aria-selected={tab===name} aria-controls="document-section-panel" id={`document-tab-${name}`} key={name} onClick={()=>setTab(name as keyof typeof sections)} className={`rounded-lg px-3 py-2 text-xs font-medium transition ${tab===name?'bg-primary/10 text-primary ring-1 ring-primary/30':'text-text-secondary hover:bg-muted hover:text-foreground'}`}>{name}</button>)}</div><div id="document-section-panel" role="tabpanel" aria-labelledby={`document-tab-${tab}`}><Section/></div><details className="mt-5 border-t border-border pt-4"><summary className="cursor-pointer text-sm font-medium">Additional information</summary><div className="mt-4 space-y-3">{(content.custom_sections||[]).map((section,i)=><div key={section.id}><input aria-label="Section title" {...methods.register(`custom_sections.${i}.title`)} className={input}/><textarea aria-label="Section content" {...methods.register(`custom_sections.${i}.content`)} rows={6} className={input}/></div>)}<Button variant="secondary" size="sm" leftIcon={<Plus className="h-3.5 w-3.5"/>} onClick={()=>methods.setValue('custom_sections',[...(content.custom_sections||[]),{id:crypto.randomUUID(),title:'Additional information',content:''}],{shouldDirty:true})}>Add section</Button></div></details></FormProvider>}</section>}
    {step===2&&<section className={`${card} space-y-4`}><div><h2 className="flex items-center gap-2 font-semibold"><Save className="h-4 w-4 text-primary"/>Save & download</h2><p className="mt-1 text-xs leading-5 text-text-secondary">Keep a private copy or share it with a client.</p></div><label className="block text-sm font-medium">Optional client copy<select value={clientId} onChange={e=>setClient(e.target.value)} className={input}><option value="">Private library only</option>{clients.map(c=><option value={c.id} key={c.id}>{c.label}</option>)}</select></label><p className="text-xs leading-5 text-text-secondary">Saving with a selected client also creates or updates their copy.</p><Button className="w-full" onClick={()=>save()} leftIcon={<Save className="h-4 w-4"/>}>Save to library{clientId?' & client':''}</Button><Button className="w-full" variant="secondary" onClick={()=>save(true)}>Save & download PDF</Button><div className="border-t border-border pt-4"><p className="mb-3 text-xs text-text-secondary">Just need a file? Download without saving.</p><div className="flex flex-wrap gap-2"><Button size="sm" variant="secondary" onClick={()=>run(()=>download('pdf'))} leftIcon={<Download className="h-3.5 w-3.5"/>}>Download PDF only</Button><Button size="sm" variant="secondary" onClick={()=>run(()=>download('docx'))} leftIcon={<Download className="h-3.5 w-3.5"/>}>Download Word only</Button></div></div></section>}
    {step<2&&<div className="flex items-center justify-between gap-3"><p className="text-xs text-text-secondary">Step {step+1} of 3</p><Button variant="secondary" onClick={()=>setStep(step+1)} rightIcon={<ArrowRight className="h-4 w-4"/>}>Continue</Button></div>}
   </div>
   <section className="min-w-0 overflow-hidden rounded-2xl border border-border bg-surface shadow-sm xl:sticky xl:top-6">
    <div className="flex flex-wrap items-center justify-between gap-3 border-b border-border px-5 py-4"><div><h2 className="font-semibold">Live preview</h2><p className="mt-1 text-xs text-text-secondary">{kind==='resume'?'Choose a layout and review every page.':'Your letter, ready for a final read.'}</p></div>{kind==='resume'&&<label className="flex items-center gap-2 text-xs text-text-secondary">Zoom<select aria-label="Preview zoom" value={zoom??'fit'} onChange={e=>setZoom(e.target.value==='fit'?null:Number(e.target.value))} className="rounded-lg border border-border bg-background px-2 py-2 text-foreground"><option value="fit">Fit width</option><option value="0.75">75%</option><option value="1">100%</option><option value="1.25">125%</option></select></label>}</div>
    {kind==='resume'&&<div className="space-y-5 border-b border-border p-5"><fieldset><legend className="mb-3 text-xs font-semibold uppercase tracking-wider text-text-secondary">Choose a template</legend><div className="grid grid-cols-3 gap-2">{templatesForType(content.resume_type||'corporate').map(t=><label key={t.id} className={`relative min-w-0 cursor-pointer rounded-xl border p-2.5 transition focus-within:ring-2 focus-within:ring-primary/40 sm:p-3 ${templateId===t.id?'border-primary bg-primary/5':'border-border hover:border-primary/40'}`}><input type="radio" name="document-template" value={t.id} checked={templateId===t.id} onChange={()=>setTemplate(t.id)} className="sr-only"/><span aria-hidden="true" className="mb-3 block rounded border border-slate-200 bg-white p-3 shadow-sm"><span className={`block text-base font-bold ${t.layout.headerStyle==='centered'?'text-center':''}`} style={{color:t.colors.primary,fontFamily:t.fonts.heading.startsWith('Times')?'Georgia,serif':'Arial,sans-serif'}}>Aa</span><span className="my-2 block h-0.5 w-full" style={{backgroundColor:t.colors.accent}}/>{[100,80,95].map((width,i)=><span key={i} className="mt-1.5 block h-1 rounded bg-slate-200" style={{width:`${width}%`}}/>)}</span><span className="block text-xs font-medium leading-5">{t.name}</span>{templateId===t.id&&<Check aria-hidden="true" className="absolute right-1 top-1 h-4 w-4 rounded-full bg-primary p-0.5 text-white"/>}</label>)}</div></fieldset><ResumeLengthSelector value={content.layout?.target_pages??null} onChange={pages=>methods.setValue('layout',{target_pages:pages},{shouldDirty:true})}/></div>}
    <div ref={previewRef} className="min-w-0 bg-muted/40"><div className="max-h-[850px] overflow-auto p-4">{kind==='resume'?<ResumePreview className="mx-auto w-fit" content={content} templateId={getTemplate(templateId).id} scale={previewScale}/>:letter?<div className="mx-auto min-h-[540px] max-w-[650px] whitespace-pre-wrap break-words rounded-sm border border-slate-200 bg-white p-6 font-serif text-sm leading-7 text-slate-900 shadow-sm sm:p-10">{letter}</div>:<div className="flex min-h-[400px] flex-col items-center justify-center px-6 text-center"><FileText className="mb-4 h-10 w-10 text-text-secondary/50"/><h3 className="text-sm font-semibold">Your cover letter starts here</h3><p className="mt-2 max-w-xs text-sm leading-6 text-text-secondary">Add candidate details, then tailor a letter to the opportunity. Your preview will appear here.</p></div>}</div></div>
   </section>
  </fieldset>
  {busy&&<p role="status" className="text-sm text-text-secondary">Working... Your draft stays editable when this finishes.</p>}
  <details className={card}><summary className="cursor-pointer font-medium"><span className="ml-2 inline-flex items-center gap-2"><FolderOpen className="h-4 w-4 text-primary"/><span>My saved {kind==='resume'?'resumes':'cover letters'}</span><span className="rounded-full bg-muted px-2 py-0.5 text-xs text-text-secondary">{savedDocuments.length}</span></span></summary>{libraryError&&<p role="alert" className="mt-3 text-sm text-error">{libraryError}</p>}{!savedDocuments.length&&!libraryError?<p className="mt-4 text-sm text-text-secondary">Your saved documents will appear here. Drafts stay private until you choose to save them.</p>:<ul className="mt-4 grid gap-3 md:grid-cols-2">{savedDocuments.map(d=><li key={d.id} className="flex min-w-0 items-center gap-3 rounded-xl border border-border bg-background/40 p-3"><FileText className="h-5 w-5 shrink-0 text-text-secondary"/><button disabled={busy} onClick={()=>open(d.id)} className="min-w-0 flex-1 text-left hover:text-primary"><span className="block truncate text-sm font-medium">{d.title}</span><span className="mt-1 block text-xs text-text-secondary">Updated {new Date(d.updated_at).toLocaleDateString()}</span></button><button disabled={busy} onClick={()=>remove(d.id)} aria-label={`Delete ${d.title}`} className="rounded-lg p-2 text-text-secondary transition hover:bg-error/10 hover:text-error"><Trash2 className="h-4 w-4"/></button></li>)}</ul>}</details>
 </div>;
}
