"use client";
import { useEffect, useRef, useState } from "react";
import { toast } from "sonner";
import { Search, ExternalLink } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Modal } from "@/components/ui/modal";
import type { JobQueueRow } from "@/types/database";
import type { AdzunaJob, AdzunaSearchParams } from "@/lib/jobs/adzuna";
import { explainJobMatch } from "@/lib/jobs/match";

type Filters = { query:string; location:string; country:string; salaryMin:string; salaryMax:string; exclude:string; age:string; employment:string; sortBy:string; fullTime:boolean };
type Saved = {id:string;title:string;filters:AdzunaSearchParams};
interface JobSearchClientProps {clientUserId?:string;defaultRole:string;defaultLocation:string;defaultCountry?:string;workType?:string;skills?:string[];resumes:{id:string;title:string;updated_at:string;kind?:"saved"|"generated"}[];queuedJobs:JobQueueRow[]}
const countries:Record<string,string>={us:"United States",in:"India",gb:"United Kingdom",ca:"Canada",au:"Australia",nz:"New Zealand",za:"South Africa",sg:"Singapore"};
const currencies:Record<string,string>={us:"USD",in:"INR",gb:"GBP",ca:"CAD",au:"AUD",nz:"NZD",za:"ZAR",sg:"SGD"};
const inputClass="mt-1 block w-full rounded-lg border border-border bg-background px-3 py-2 text-sm";
function fromParams(p:AdzunaSearchParams):Filters{return {query:p.query,location:p.location||"",country:p.country||"us",salaryMin:p.salaryMin?.toString()||"",salaryMax:p.salaryMax?.toString()||"",exclude:p.exclude||"",age:p.maxDaysOld?.toString()||"",employment:p.employment||"any",sortBy:p.sortBy||"relevance",fullTime:p.fullTime===true};}
export function JobSearchClient({clientUserId,defaultRole,defaultLocation,defaultCountry="us",workType="any",skills=[],resumes,queuedJobs}:JobSearchClientProps){
  const [filters,setFilters]=useState<Filters>(()=>fromParams({query:defaultRole,location:defaultLocation,country:countries[defaultCountry]?defaultCountry:"us"}));
  const [results,setResults]=useState<AdzunaJob[]>([]);const [total,setTotal]=useState(0);const [page,setPage]=useState(1);
  const [searching,setSearching]=useState(false);const [searched,setSearched]=useState(false);const [error,setError]=useState("");const [warning,setWarning]=useState("");const [searchedAt,setSearchedAt]=useState("");
  const [activeFilters,setActiveFilters]=useState<Filters|null>(null);const [selected,setSelected]=useState<Record<string,AdzunaJob>>({});const [detail,setDetail]=useState<AdzunaJob|null>(null);const [review,setReview]=useState(false);
  const [queue,setQueue]=useState(queuedJobs);const [queueing,setQueueing]=useState(false);const [showQueue,setShowQueue]=useState(false);
  const [resume,setResume]=useState(resumes.length ? `${resumes[0].kind||"saved"}:${resumes[0].id}` : "");
  const [saved,setSaved]=useState<Saved[]>([]);const [saveTitle,setSaveTitle]=useState("");const [saving,setSaving]=useState(false);
  const [rankMatches,setRankMatches]=useState(false);const [dismissed,setDismissed]=useState<Set<string>>(new Set());
  const searchAbort=useRef<AbortController|null>(null);const requestId=useRef(0);const queuePending=useRef(false);
  useEffect(()=>{
    const controller=new AbortController();
    fetch('/api/jobs/saved-searches',{signal:controller.signal}).then(r=>r.json()).then(data=>{if(data.success)setSaved(data.data);}).catch(()=>{});
    const raw=new URLSearchParams(window.location.search).get('search');
    if(raw){try{const parsed=JSON.parse(raw);if(typeof parsed.query==='string'&&countries[parsed.country])setFilters(fromParams(parsed));}catch{/* Ignore invalid bookmarks. */}}
    return()=>{controller.abort();searchAbort.current?.abort();};
  },[]);
  const set=(key:keyof Filters,value:string|boolean)=>setFilters(prev=>({...prev,[key]:value}));
  function params(f:Filters,p=1):AdzunaSearchParams{return {query:f.query.trim(),location:/^remote$/i.test(f.location.trim())?"":f.location.trim(),country:f.country,page:p,resultsPerPage:20,sortBy:f.sortBy as AdzunaSearchParams['sortBy'],salaryMin:f.salaryMin?Number(f.salaryMin):undefined,salaryMax:f.salaryMax?Number(f.salaryMax):undefined,maxDaysOld:f.age?Number(f.age):undefined,exclude:f.exclude.trim(),employment:f.employment as AdzunaSearchParams['employment'],fullTime:f.fullTime?true:undefined};}
  async function search(f=filters,p=1){
    if(!f.query.trim()){setError("Enter a title or keyword.");return;}
    if(f.salaryMin&&f.salaryMax&&Number(f.salaryMax)<Number(f.salaryMin)){setError("Maximum salary must be at least the minimum.");return;}
    searchAbort.current?.abort();const controller=new AbortController();searchAbort.current=controller;const sequence=++requestId.current;
    setSearching(true);setError("");setWarning("");
    try{const response=await fetch(clientUserId?'/api/admin/jobs/search':'/api/jobs/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(params(f,p)),signal:controller.signal});const data=await response.json();if(!response.ok)throw Error(data.error?.message||'Search failed. Please retry.');if(sequence!==requestId.current)return;
      setResults(data.data.jobs);setTotal(data.data.totalResults);setPage(p);setSearched(true);setActiveFilters({...f});setSearchedAt(data.data.searchedAt||new Date().toISOString());setWarning(data.data.warning||'');setDetail(null);
      const url=new URL(window.location.href);url.searchParams.set('search',JSON.stringify(params(f,p)));window.history.replaceState(null,'',url);
    }catch(e){if(!controller.signal.aborted&&sequence===requestId.current)setError(e instanceof Error?e.message:'Search unavailable.');}
    finally{if(sequence===requestId.current)setSearching(false);}
  }
  async function saveSearch(){setSaving(true);try{const r=await fetch('/api/jobs/saved-searches',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:saveTitle,filters:params(filters)})});const data=await r.json();if(!r.ok)throw Error(data.error?.message||'Unable to save');setSaved(prev=>[data.data,...prev]);setSaveTitle('');toast.success('Search saved.');}catch(e){toast.error(e instanceof Error?e.message:'Unable to save');}finally{setSaving(false);}}
  const queued=new Map(queue.map(job=>[job.job_url,job.status]));
  const preferences={role:defaultRole||activeFilters?.query||filters.query,location:defaultLocation,skills,workType};
  const visible=results.filter(job=>!dismissed.has(job.id));
  if(rankMatches)visible.sort((a,b)=>explainJobMatch(b,preferences).score-explainJobMatch(a,preferences).score);
  async function enqueue(){
    if(queuePending.current)return;queuePending.current=true;setQueueing(true);
    try{const [kind,id]=resume.split(':');const response=await fetch(clientUserId?'/api/admin/jobs/queue':'/api/jobs/queue',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...(clientUserId?{user_id:clientUserId}:{}),jobs:Object.values(selected).map(job=>({catalog_id:job.catalog_id,job_url:job.job_url})),resume_id:kind==='saved'?id:null,admin_resume_id:kind==='generated'?id:null})});const data=await response.json();if(!response.ok)throw Error(data.error?.message||'Unable to queue jobs.');setQueue(prev=>[...new Map([...(data.data.jobs||[]),...prev].map((job:JobQueueRow)=>[job.id,job])).values()]);setSelected({});setReview(false);toast.success(`${data.data.added} jobs added. Existing entries were kept.`);}catch(e){toast.error(e instanceof Error?e.message:'Unable to queue jobs.');}finally{queuePending.current=false;setQueueing(false);}
  }
  const text=(key:keyof Filters,label:string,type='text')=><label className="text-sm">{label}<input value={String(filters[key])} onChange={e=>set(key,e.target.value)} type={type} min={type==='number'?0:undefined} className={inputClass}/></label>;
  return <div className="space-y-5">
    <form onSubmit={e=>{e.preventDefault();void search();}} className="rounded-xl border border-border bg-surface p-4 sm:p-6 space-y-4">
      <div className="grid gap-4 sm:grid-cols-2">{text('query','Job title / keywords')}{text('location','City or region (leave blank for nationwide)')}
        <label className="text-sm">Country<select value={filters.country} onChange={e=>setFilters(prev=>({...prev,country:e.target.value,location:'',salaryMin:'',salaryMax:''}))} className={inputClass}>{Object.entries(countries).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></label>
        <label className="text-sm">Sort by<select value={filters.sortBy} onChange={e=>set('sortBy',e.target.value)} className={inputClass}><option value="relevance">Provider relevance</option><option value="date">Newest first</option><option value="salary">Salary</option></select></label>
      </div>
      <details><summary className="cursor-pointer text-sm font-medium">More filters</summary><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {text('salaryMin',`Minimum annual salary (${currencies[filters.country]})`,'number')}{text('salaryMax',`Maximum annual salary (${currencies[filters.country]})`,'number')}{text('exclude','Exclude keywords')}
        <label className="text-sm">Posted within<select value={filters.age} onChange={e=>set('age',e.target.value)} className={inputClass}><option value="">Any time</option>{[1,3,7,14,30].map(day=><option key={day} value={day}>{day} days</option>)}</select></label>
        <label className="text-sm">Employment type<select value={filters.employment} onChange={e=>set('employment',e.target.value)} className={inputClass}><option value="any">Any</option><option value="permanent">Permanent</option><option value="contract">Contract</option></select></label>
        <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={filters.fullTime} onChange={e=>set('fullTime',e.target.checked)}/>Full time only</label>
      </div></details>
      <p className="text-xs text-text-secondary">For remote roles, include “remote” in keywords. Work arrangement and sponsorship still need verification in the original listing.</p>
      <div className="flex flex-wrap gap-3 items-center"><Button type="submit" isLoading={searching} leftIcon={<Search className="h-4 w-4"/>}>Search jobs</Button><button type="button" className="text-sm underline" onClick={()=>setShowQueue(!showQueue)}>Queue ({queue.length})</button></div>
    </form>
    <details className="rounded-xl border border-border p-4"><summary className="text-sm cursor-pointer">Saved searches ({saved.length})</summary><div className="mt-3 flex flex-wrap items-end gap-2"><label className="text-sm flex-1">Search name<input value={saveTitle} onChange={e=>setSaveTitle(e.target.value)} maxLength={100} className={inputClass}/></label><Button disabled={!saveTitle.trim()||!filters.query.trim()||saving} onClick={saveSearch}>Save current filters</Button></div><ul className="mt-3 space-y-2">{saved.map(item=><li key={item.id} className="flex justify-between gap-3 text-sm"><button className="underline" onClick={()=>{const f=fromParams(item.filters);setFilters(f);void search(f);}}>{item.title}</button><button className="text-error" onClick={async()=>{const r=await fetch(`/api/jobs/saved-searches?id=${item.id}`,{method:'DELETE'});if(r.ok)setSaved(prev=>prev.filter(s=>s.id!==item.id));else toast.error('Unable to remove saved search.');}}>Remove</button></li>)}</ul></details>
    {showQueue&&<section className="rounded-xl border border-border p-4"><h2 className="font-semibold">Application queue</h2>{!queue.length&&<p className="text-sm mt-2">No queued jobs yet.</p>}<ul className="mt-3 max-h-72 overflow-auto space-y-2">{queue.map(job=><li key={job.id} className="flex justify-between gap-3 text-sm"><span>{job.title} · {job.company}</span><span>{job.status}</span></li>)}</ul></section>}
    {error&&<p role="alert" className="rounded-lg border border-error/30 p-3 text-sm text-error">{error}{searched?' Previous results remain below.':''}</p>}
    {warning&&<p role="status" className="text-sm text-warning">{warning}</p>}
    {searched&&<div className="flex flex-wrap gap-3 items-center justify-between"><div className="text-sm"><p>{total.toLocaleString()} results · Page {page} · {countries[activeFilters?.country||filters.country]}</p><p className="text-xs text-text-secondary">{activeFilters?.query} · {activeFilters?.location||'Nationwide'} · Retrieved {new Date(searchedAt).toLocaleTimeString()}</p></div><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={rankMatches} onChange={e=>setRankMatches(e.target.checked)}/>Rank this page by profile match</label></div>}
    {!!Object.keys(selected).length&&<div className="sticky top-2 z-20 flex flex-wrap justify-between items-center gap-3 rounded-xl border border-primary/30 bg-surface p-3"><p className="text-sm">{Object.keys(selected).length} jobs shortlisted</p><Button onClick={()=>setReview(true)}>Review selected jobs</Button></div>}
    <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_minmax(280px,0.75fr)]"><div className="space-y-3">
      {visible.map(job=>{const match=explainJobMatch(job,preferences);const status=queued.get(job.job_url);return <article key={job.id} className="rounded-xl border border-border bg-surface p-4 space-y-2"><div className="flex items-start justify-between gap-3"><button onClick={()=>setDetail(job)} className="text-left font-semibold hover:underline">{job.title}</button>{status?<span className="text-xs text-success capitalize">{status}</span>:<label className="flex gap-2 text-xs"><input type="checkbox" aria-label={`Shortlist ${job.title}`} disabled={!job.catalog_id} checked={!!selected[job.id]} onChange={e=>setSelected(prev=>{const next={...prev};if(e.target.checked)next[job.id]=job;else delete next[job.id];return next;})}/>Shortlist</label>}</div><p className="text-sm text-text-secondary">{job.company} · {job.location||'Location not specified'}</p><p className="text-sm">{job.salary_text} {job.salary_predicted?'(estimated)':''}</p><p className="text-xs text-text-secondary">{job.created?`Posted ${new Date(job.created).toLocaleDateString()}`:'Posting date unknown'} · {job.work_arrangement==='unknown'?'Work arrangement unknown':`${job.work_arrangement} mentioned`}</p><p className="text-sm line-clamp-2 text-text-secondary">{job.description}</p>{match.reasons.length>0&&<p className="text-xs text-primary">{match.reasons.join(' · ')}</p>}<div className="flex gap-4 text-xs"><a href={job.job_url} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 underline">Original listing<ExternalLink className="h-3 w-3"/></a><button onClick={()=>{setDismissed(prev=>new Set(prev).add(job.id));setSelected(prev=>{const next={...prev};delete next[job.id];return next;});}}>Dismiss for this session</button></div></article>;})}
      {!searching&&!visible.length&&<p className="rounded-xl border border-dashed border-border p-8 text-sm text-text-secondary">{searched?'No visible jobs match this search. Try broader titles, remove salary/exclusion filters, or change the location.':'Choose a role and location to search for jobs.'}</p>}
      {!!dismissed.size&&<button className="text-sm underline" onClick={()=>setDismissed(new Set())}>Restore dismissed jobs</button>}
    </div><aside className="self-start rounded-xl border border-border p-4 xl:sticky xl:top-4">{detail?<><h2 className="font-semibold">{detail.title}</h2><p className="mt-1 text-sm">{detail.company} · {detail.location}</p><p className="my-4 whitespace-pre-wrap text-sm">{detail.description}</p><h3 className="font-medium text-sm">Match evidence</h3><ul className="my-2 space-y-1 text-xs">{explainJobMatch(detail,preferences).reasons.map(reason=><li key={reason}>{reason}</li>)}</ul><h3 className="font-medium text-sm">Review before applying</h3><ul className="my-2 space-y-1 text-xs text-text-secondary">{explainJobMatch(detail,preferences).gaps.map(gap=><li key={gap}>{gap}</li>)}</ul><a href={detail.job_url} target="_blank" rel="noopener noreferrer" className="text-sm text-primary underline">Read full listing on source site</a></>:<p className="text-sm text-text-secondary">Select a job title to review the description and match evidence.</p>}</aside></div>
    {searched&&<div className="flex justify-between items-center gap-3"><Button variant="secondary" disabled={searching||page<=1} onClick={()=>search(activeFilters||filters,page-1)}>Previous</Button><span className="text-xs">Page {page} of {Math.max(1,Math.ceil(total/20))}</span><Button variant="secondary" disabled={searching||page*20>=total} onClick={()=>search(activeFilters||filters,page+1)}>Next</Button></div>}
    <p className="text-xs text-text-secondary">Jobs by <a href="https://www.adzuna.com" target="_blank" rel="noopener noreferrer" className="underline">Adzuna</a>. Match evidence uses professional preferences only; it is not a hiring probability.</p>
    <Modal open={review} onClose={()=>{if(!queuePending.current)setReview(false);}} title="Review selected jobs" hideCloseButton={queueing} closeOnOverlayClick={!queueing}><div className="space-y-4"><p className="text-sm">Review these jobs and the resume before adding them to {clientUserId?'the selected client’s':'your'} application queue. This does not submit applications.</p><label className="text-sm">Resume<select value={resume} onChange={e=>setResume(e.target.value)} disabled={queueing} className={inputClass}><option value="">No resume attached</option>{resumes.map(item=><option key={`${item.kind}:${item.id}`} value={`${item.kind||'saved'}:${item.id}`}>{item.title}{item.kind==='generated'?' · Recruiter generated':''}</option>)}</select></label><ul className="space-y-3">{Object.values(selected).map(job=><li key={job.id} className="flex justify-between gap-3 text-sm"><span>{job.title} · {job.company}</span><button disabled={queueing} onClick={()=>setSelected(prev=>{const next={...prev};delete next[job.id];return next;})}>Remove</button></li>)}</ul><Button disabled={queueing||!Object.keys(selected).length} isLoading={queueing} onClick={enqueue}>Add reviewed jobs to queue</Button></div></Modal>
  </div>;
}
